"""
Detección de WAF (Web Application Firewall) y CDN.
Usa wafw00f si está disponible, con fallback nativo.
"""
import re
import json
from modules.core.engine import run_cmd, check_tool
from modules.core.logger import console, get_logger
from modules.core.storage import Storage

log = get_logger("waf.detector")

try:
    import requests
    import urllib3
    urllib3.disable_warnings()
    _REQUESTS_OK = True
except ImportError:
    _REQUESTS_OK = False

# Firmas WAF en headers y cuerpos de respuesta
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "server":  ["cloudflare"],
        "body":    ["cloudflare", "attention required", "__cf_chl"],
    },
    "Akamai": {
        "headers": ["akamai-x-check-cacheable", "x-akamai-request-id"],
        "server":  ["akamaighost", "akamaierror"],
        "body":    ["akamai", "reference #"],
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "server":  ["incapsula"],
        "body":    ["incapsula incident id", "_incap_session"],
        "cookies": ["visid_incap", "incap_ses"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "server":  [],
        "body":    ["aws waf", "request blocked"],
    },
    "F5 BIG-IP": {
        "headers": ["x-waf-event-info"],
        "server":  ["bigip", "big-ip"],
        "cookies": ["ts", "f5_cspm"],
        "body":    ["the requested url was rejected"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "server":  ["sucuri/cloudproxy"],
        "body":    ["access denied - sucuri website firewall"],
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "cookies": ["barra_counter_session"],
        "body":    ["barracuda", "you have been blocked"],
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "fastly-io-warning"],
        "server":  ["varnish"],
        "body":    [],
    },
    "Nginx WAF": {
        "headers": [],
        "server":  ["nginx"],
        "body":    ["nginx", "access forbidden"],
    },
    "ModSecurity": {
        "headers": ["x-protected-by", "x-mod-pagespeed"],
        "server":  [],
        "body":    ["not acceptable!", "modsecurity", "this error was generated by mod_security"],
    },
}

# Payloads para trigger WAF
WAF_TRIGGER_PAYLOADS = [
    "/?test=<script>alert(1)</script>",
    "/?test=UNION+SELECT+1,2,3--",
    "/?test=../../../etc/passwd",
    "/?test='; DROP TABLE users;--",
]


class WAFDetector:
    MODULE_NAME = "waf"

    def __init__(self, config: dict, storage: Storage):
        self.config  = config
        self.storage = storage
        self.cfg     = config.get("waf", {})
        self.has_wafw00f = check_tool("wafw00f")

    def run(self, targets: list[str]) -> dict:
        """
        Detecta WAF en los targets HTTP.
        Retorna dict {target: {detected, waf_name, confidence}}.
        """
        results = {}
        console.print(f"  [module]WAF Detection[/] → {len(targets)} targets")

        for target in targets:
            url = target if target.startswith("http") else f"https://{target}"
            host = re.sub(r"https?://", "", url).split("/")[0]

            if self.has_wafw00f:
                detection = self._run_wafw00f(url)
            else:
                detection = self._detect_native(url)

            results[host] = detection

            if detection["detected"]:
                console.print(
                    f"  [warning]WAF detectado:[/] [bold]{detection['waf_name']}[/] "
                    f"en {host} (confianza: {detection['confidence']})"
                )

                self.storage.add_finding(
                    title=f"WAF detectado: {detection['waf_name']} en {host}",
                    severity="info",
                    module=self.MODULE_NAME,
                    description=(
                        f"Se detectó el WAF/CDN '{detection['waf_name']}' en {host}. "
                        f"Confianza: {detection['confidence']}. "
                        f"Tener en cuenta para fuzzing y exploits."
                    ),
                    host=host,
                    evidence=detection.get("evidence", ""),
                    tags=["waf", "cdn", detection["waf_name"].lower().replace(" ", "-")],
                )

        self.storage.save_module(self.MODULE_NAME, {"results": results})
        console.print(
            f"  [success]✓[/] WAF detection completado"
        )
        return {"results": results}

    def _run_wafw00f(self, url: str) -> dict:
        """Usa wafw00f para detección."""
        cmd = ["wafw00f", "-a", url, "-o", "json"]
        rc, stdout, stderr = run_cmd(cmd, timeout=60)

        try:
            data = json.loads(stdout)
            if isinstance(data, list) and data:
                entry = data[0]
                waf = entry.get("waf", "Unknown")
                manufacturer = entry.get("manufacturer", "")
                if waf and waf.lower() not in ("none", "unknown", ""):
                    return {
                        "detected":   True,
                        "waf_name":   f"{waf} ({manufacturer})" if manufacturer else waf,
                        "confidence": "high",
                        "method":     "wafw00f",
                        "evidence":   stdout[:500],
                    }
        except Exception:
            # Parsear stdout de texto plano
            for line in stdout.splitlines():
                if "is behind" in line.lower():
                    # "[*] example.com is behind Cloudflare WAF"
                    m = re.search(r"is behind (.+?)(?:\s+WAF)?$", line, re.IGNORECASE)
                    if m:
                        return {
                            "detected":   True,
                            "waf_name":   m.group(1).strip(),
                            "confidence": "high",
                            "method":     "wafw00f",
                            "evidence":   line,
                        }

        # Fallback nativo si wafw00f no devolvió nada útil
        return self._detect_native(url)

    def _detect_native(self, url: str) -> dict:
        """Detección nativa: analiza headers y respuestas a payloads."""
        if not _REQUESTS_OK:
            return {"detected": False, "waf_name": "", "confidence": "none", "method": "none"}

        detected_wafs = []
        evidence_lines = []

        try:
            # Primera petición normal para analizar headers de base
            r = requests.get(
                url,
                timeout=10,
                verify=False,
                headers={"User-Agent": "Mozilla/5.0 OrionRecon"},
                allow_redirects=True,
            )

            # Analizar headers y cookies
            header_keys_lower = {k.lower(): v.lower() for k, v in r.headers.items()}
            body_lower        = r.text[:3000].lower()
            cookies_lower     = {k.lower(): v.lower() for k, v in r.cookies.items()}

            for waf_name, sigs in WAF_SIGNATURES.items():
                score = 0

                for h in sigs.get("headers", []):
                    if h.lower() in header_keys_lower:
                        score += 2
                        evidence_lines.append(f"Header: {h}")

                for s in sigs.get("server", []):
                    server_header = header_keys_lower.get("server", "")
                    if s.lower() in server_header:
                        score += 2
                        evidence_lines.append(f"Server: {server_header}")

                for b in sigs.get("body", []):
                    if b.lower() in body_lower:
                        score += 1
                        evidence_lines.append(f"Body pattern: {b}")

                for c in sigs.get("cookies", []):
                    if c.lower() in cookies_lower:
                        score += 2
                        evidence_lines.append(f"Cookie: {c}")

                if score >= 2:
                    detected_wafs.append((waf_name, score))

        except Exception as e:
            log.debug(f"Error en petición base WAF para {url}: {e}")

        # Probar payloads de trigger
        if not detected_wafs and _REQUESTS_OK:
            for payload in WAF_TRIGGER_PAYLOADS[:2]:
                try:
                    test_url = url.rstrip("/") + payload
                    r2 = requests.get(
                        test_url,
                        timeout=8,
                        verify=False,
                        headers={"User-Agent": "Mozilla/5.0"},
                        allow_redirects=True,
                    )
                    # Si recibimos 403/406/429 con cuerpo típico de WAF
                    if r2.status_code in (403, 406, 429, 503):
                        body2 = r2.text[:2000].lower()
                        for waf_name, sigs in WAF_SIGNATURES.items():
                            for b in sigs.get("body", []):
                                if b.lower() in body2:
                                    detected_wafs.append((waf_name, 1))
                                    evidence_lines.append(
                                        f"Trigger payload '{payload}' → {r2.status_code}: {b}"
                                    )
                                    break
                except Exception as e:
                    log.debug(f"WAF payload probe error for {url}: {e}")

        if detected_wafs:
            # Tomar el WAF con mayor score
            best = max(detected_wafs, key=lambda x: x[1])
            confidence = "high" if best[1] >= 4 else "medium" if best[1] >= 2 else "low"
            return {
                "detected":   True,
                "waf_name":   best[0],
                "confidence": confidence,
                "method":     "native",
                "evidence":   "\n".join(evidence_lines[:5]),
            }

        return {
            "detected":   False,
            "waf_name":   "",
            "confidence": "high",
            "method":     "native",
            "evidence":   "",
        }
